# Site Settings
locale                   : "en-US"
title                    : "Franck Portier"
title_separator          : "-"
name                     : &name "Franck Portier"
description              : &description "Professor of Economics, University College London"
url                      : "https://fpjportier.github.io"
baseurl                  : ""
repository               : "fpjportier/fpjportier.github.io"

# Site Author
author:
  name             : *name
  avatar           : # path of avatar image, e.g. "images/photo.jpg"
  bio              : "Professor of Economics at University College London. Research interests: macroeconomics, business cycles, monetary policy, expectations."
  location         : "London, United Kingdom"
  employer         : "University College London"
  email            : "f.portier@ucl.ac.uk"
  uri              : "https://fpjportier.github.io"
  googlescholar    : "http://scholar.google.fr/citations?user=Pk9mBK4AAAAJ"
  orcid            : "https://orcid.org/0000-0001-9409-3946"
  repec            : "https://ideas.repec.org/e/ppo12.html"
  twitter          : "FpjPortier"

# Reading Files
include:
  - .htaccess
  - _pages

# Exclude from processing.
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_codespan_class: false
  parse_span_html: true
  parse_block_html: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/London

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:title/
  talks:
    output: true
    permalink: /:collection/:title/
  teaching:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
